<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">	


  <div class="jumbotron">
    <h1>Dynamische ProduktKatalog</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum eos cupiditate vel nam possimus modi nostrum hic amet praesentium mollitia, pariatur officia soluta quo sed, inventore, fugit delectus incidunt odit!</p>
    <a class="btn btn-lg btn-primary" href="#" role="button">View navbar docs &raquo;</a>
  </div>

  <div class="col-md-12">
  	<?php foreach($this->products as $product):?>
  	<div class="col-md-4">
  		<img src="https://via.placeholder.com/350x150" alt="" class="img-responsive">
  		<h2><a href="<?=HOME;?>/product/<?=$product['id'];?>"><?=$product['name'];?></a></h2>
  		<p><?=$product['description'];?></p>
  		<p><?=number_format($product['price'], 2, ',', '.');?></p>
  	</div>
  	<?php endforeach; ?>
  </div>

</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>